join:
  joinMessage: true
  broadcast: "[&a+&r] "
  custom1: "&6[&9Hera&6] &rBienvenue à toi &b"
  custom2: "&r sur ce serveur !"

config:
  spawn_x: 0
  spawn_y: 0
  spawn_z: 0

leave:
  leaveMessage: true
  broadcast: "[&4-&r] "

antiVPN:
  activate: true
  4G: true
  hosting: true
  proxy: true

WebhooksDiscord:
  activate: true
  PluginUpDown: ""