join:
  joinMessage: true
  broadcast: "[&a+&r] "
  custom1: "&6[&9Hera&6] &rBienvenue à toi &b"
  custom2: "&r sur ce serveur !"

config:
  spawn: "0,0,0"

leave:
  leaveMessage: true
  broadcast: "[&4-&r] "

antiVPN:
  activate: false
  4G: true
  hosting: true
  proxy: true

WebhooksDiscord:
  activate: false

blacklist:
  - con
  - connard