name: Hera
version: '${project.version}'
main: fr.whitefox.hera.Main
authors: [ WhiteFox2232 ]
description: Hera is a Minecraft plugin for community server events. It facilitates the work of event managers
website: https://github.com/TechdevOS/Hera

commands:
  tpall:
    description: Commande permettant de tp l'entièreté du serveur sur la position de l'executeur
    permission: hera.tpall
  dupeip:
    description: Get IP address of a Player
    permission: hera.dupeip
  vanish:
    description: Devenez invisible !
    permission: hera.vanish
  gm:
    description: Permet de changer votre mode de jeu
    permission: hera.gm
  heal:
    description: Permet de vous régénérer
    permission: hera.heal
  feed:
    description: Permet de remettre votre niveau de nourriture au maxiumum
    permission: hera.feed
  spawn:
    description: Revenir au spawn
    permission: hera.spawn
  s:
    description: Permet de /stop le serveur avec raison
    permission: hera.stop
  rain:
    description: Permet de mettre de la pluie
    permission: hera.weather
  thunder:
    description: Permet de mettre de l'orage
    permission: hera.weather
  sun:
    description: Permet de clear la pluie et l'orage
    permission: hera.weather
  wl:
    description: Set Whitelist
    permission: hera.wl
  antivpn:
    description: Permet d'activer ou désactiver l'antiVPN
    permission: hera.antivpn
  debug:
    description: Debug Command
    permission: hera.debug
  freeze:
    description: Permet de freeze un joueur
    permission: hera.freeze
  fly:
    description: Permet de se mettre en fly
    permission: hera.fly
  day:
    description: Permet de définir le monde sur jour
    permission: hera.time
  night:
    description: Permet de définir le monde sur nuit
    permission: hera.time
  kick:
    description: Permet d'éjecter un joueur du serveur
    permission: hera.kick
  pday:
    description: Permet de définir la vision du joueur sur jour
    permission: hera.time
  pnight:
    description: Permet de définir le vision du joueur sur nuit
    permission: hera.time
  ban:
    description: Permet de bannir temporairement ou définitivement un joueur
    permission: hera.ban
  unban:
    description: Permet de débannir un joueur
    permission: hera.ban
  mute:
    description: Permet de mute un joueur
    permission: hera.mute
  unmute:
    description: Permet d'unmute un joueur
    permission: hera.mute