name: Hera
version: '${project.version}'
main: fr.whitefox.hera.Main
authors: [ WhiteFox2232 ]
description: A Minecraft Plugin
website: https://github.com/WhiteFox2232

commands:
  alert:
    description: Commande permettant de faire des annonces
    permission: hera.alert
  down:
    description: Commande permettant de stop le serveur au bout de 10 secondes
    permission: hera.down
  tpall:
    description: Commande permettant de tp l'entièreté du serveur sur la position de l'executeur
    permission: hera.tpall
  dupeip:
    description: Get IP address of a Player
    permission: hera.dupeip
  vanish:
    description: Devenez invisible !
    permission: hera.vanish
  staffhat:
    description: Commande permettant de vous mettre un chapeau de staff :)
    permission: hera.staffhat
  update:
    description: Dev Command
    permission: hera.dev
  p:
    description: Fait apparaître des particules
    permission: hera.particule