name: Hera
version: '${project.version}'
main: fr.whitefox.hera.Main
authors: [ WhiteFox2232 ]
description: A Minecraft Plugin
website: https://github.com/WhiteFox2232

commands:
  alert:
    description: Commande permettant de faire des annonces
    permission: palanim.alert
  down:
    description: Commande permettant de stop le serveur au bout de 10 secondes
    permission: palanim.down
  tpall:
    description: Commande permettant de tp l'entièreté du serveur sur la position de l'executeur
    permission: palanim.tpall
  clean:
    description: Commande permettant de clear le chat
    permission: palanim.clean
  staffhat:
    description: Commande permettant de vous mettre un chapeau de staff :)
    permission: palanim.staffhat
  update:
    description: Dev Command
    permission: palanim.dev
  spawn:
    description: Commande permettant de se rendre au spawn
    permission: palanim.spawn
  p:
    description: Fait apparaître des particules
    permission: palanim.particule