name: Hera
version: '${project.version}'
main: fr.whitefox.hera.Main
authors: [ WhiteFox2232 ]
description: A Minecraft Plugin
website: https://github.com/WhiteFox2232

commands:
  down:
    description: Commande permettant de stop le serveur au bout de 10 secondes
    permission: hera.down
  tpall:
    description: Commande permettant de tp l'entièreté du serveur sur la position de l'executeur
    permission: hera.tpall
  dupeip:
    description: Get IP address of a Player
    permission: hera.dupeip
  vanish:
    description: Devenez invisible !
    permission: hera.vanish
  staffhat:
    description: Commande permettant de vous mettre un chapeau de staff :)
    permission: hera.staffhat
  update:
    description: Dev Command
    permission: hera.dev
  gm:
    description: Permet de changer votre mode de jeu
    permission: hera.gm
  heal:
    description: Permet de vous régénérer
    permission: hera.heal
  feed:
    description: Permet de remettre votre niveau de nourriture au maxiumum
    permission: hera.feed
  spawn:
    description: Revenir au spawn
    permission: hera.spawn
  s:
    description: Permet de /stop le serveur avec raison
    permission: hera.stop